### PR TITLE
Fixes to test figure output and multi-platform support

### PR DESCRIPTION
**Pull request by adigitoleo**
- Use PDF for all figures
- Remove redundant old plotting functions
- Use a safe wrapper to get a default number of CPUs for Linux, Mac or Windows
- Make the `venv_install.sh` script support `PYTHON_BINARY` for using custom paths to local Python installations (e.g. 3.11 on cosgrove)

### CODE REVIEW

**Comment by adigitoleo** [comment]
Could be useful to add runners for CI on `windows-latest` and `macos-latest` as well, might look at that later tonight.

**Review by Patol75 — APPROVED** [review]
Changes look sensible to me :)

**Review by Patol75 — DISMISSED** [review]

**Review by Patol75 — APPROVED** [review]

**Comment by adigitoleo** [comment]
Failing on Windows because of strangely large memory commits from scipy integrators (switching back to RK45 doesn't help). Tempted to drop Windows support for now. Potentially related to the SciPy BLAS being different on windows (I think?) or maybe an actual SciPy integrator bug on windows. MacOS is passing.

**Comment by Patol75** [comment]
Perhaps drop Windows for now. It could just be running out of memory. Not quite sure why that would not be the case on Ubuntu though.

**Review by Patol75 — APPROVED** [review]

**Pull request merged**
