### PR TITLE
Fluidity advection 2d

### PR DESCRIPTION
**Pull request by adigitoleo**
Add fluidity advection example and simple builtin mesh (gmsh) generation.

### CODE REVIEW

**Comment by adigitoleo** [comment]
Failures caused by gmsh not being able to find its dependency:

```
OSError: libGLU.so.1: cannot open shared object file: No such file or directory
```

**Comment by adigitoleo** [comment]
Tracked it down: docs failure is still caused by gmsh import, the workaround from https://github.com/seismic-anisotropy/PyDRex/pull/174/commits/2d30d913c1a90361df7806a12c1248a3d0b9751e doesn't fix it. Since the gmsh package is so much trouble I'll just move it to an optional dep and make the mesh generation functionality unavailable by default.

**Comment by adigitoleo** [comment]
https://github.com/mitmproxy/pdoc/issues/673

**Comment by adigitoleo** [comment]
Manual exclusion of the `mesh` submodule from the docs works for now.

**Comment by adigitoleo** [comment]
Fluidity now seems to produce the correct results. More on this later today. Might want to squash some of this stuff before merge.

**Review by Patol75 — DISMISSED** [review]

**Review by Patol75 — APPROVED** [review]

**Pull request merged**
